### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by oraibalmegdadi** [Vangos/KinectHtml5#1]
Hello ,, 
I installed the Kinect and microsoft SDK, and the kinect is working with other application .. 
I clone the kinectHtml5 project at my desktop .. and i did not add or change anything to the github code
I run the server application at my machine and a console appear telling my i am connected to local host ... 
then i open the index.html file at chrome, the status at chrome is " Status: Connection successful. " and at the console, connected to 127.0.0.1
i stand up in front of the kinec, 
According to pictures at codeprojects, the output should be points, but the output is pointed connected with lines in my program ...   

did i miss something ???? 

and if i want the kinect to handle one gesture, is that possible ?

**Comment by Vangos** [comment]
Hi,

Regarding the gesture, yes, it is possible to recognise it. You need to to do it server-side for better performance. A successfully recognised gesture should trigger an event, and then the WebSocket should send the corresponding data to the client. You can use https://github.com/EvilClosetMonkey/Fizbin.Kinect.Gestures for gesture recognition.

Regarding the drawing issue, do you get straight lines from joint to joint or something else?

**Comment by oraibalmegdadi** [comment]
Hello ,,, 
Thank you; I will check the gesture recognition solution you suggested ... 
I am thinking to recognize the gesture at client side, i think it will be faster and better than sending the data to the server and then send back the information to the client, because i notice that the application is slow, and do not start immediately..  
According to the  drawing; i get big joints connected with lines and filled area between lines ... 
![image](https://f.cloud.github.com/assets/4184460/1660938/5cdb7a80-5bcd-11e3-97d0-0681647595fd.png)

**Comment by Vangos** [comment]
Hi again. Apologies for my late reply. I updated the JavaScript file and it now works fine.

Here is the new repository for this project: https://github.com/LightBuzz/Kinect-HTML5
